### ISSUE TITLE
Wrong result in addition or subtraction.

### ISSUE THREAD

**Issue by pathakumesh** [eoyilmaz/timecode#19]
While adding or subtracting two timecode objects, the result differs:
- ### Addition
```
>>>Timecode(25, '00:00:00:03') + Timecode(25, '00:00:00:06')
00:00:00:10
```
It should be `00:00:00:09` 
<img width="507" alt="Screen Shot 2019-11-02 at 7 15 25 AM" src="https://user-images.githubusercontent.com/10126570/68064187-90c3dc00-fd40-11e9-93f6-ecf1c8ad76e4.png">

- ### Subtraction
```
>>> Timecode(25, '00:00:00:23') - Timecode(25, '00:00:00:20')
00:00:00:02
```
It should be `00:00:00:03` 
<img width="523" alt="Screen Shot 2019-11-02 at 7 14 19 AM" src="https://user-images.githubusercontent.com/10126570/68064180-77229480-fd40-11e9-9a14-61c816d164a0.png">

Online tool used for cross validation: http://www.michaelcinquin.com/tools/timecode_keykode

**Comment by eksod** [comment]
Hey! I have also been getting some what appears to be some frames off by subtracting 29.97 timecodes:

```
>>> vid = Timecode(29.97, "09:16:16:24")
>>> clip = Timecode(29.97, "09:16:17:13")
>>> clip - vid
00:00:00;18
```
![image](https://user-images.githubusercontent.com/490588/68217999-e9ff6a00-ffe3-11e9-96e5-758c5dbf3cc1.png)


```
>>> vid = Timecode(29.97, "09:23:56:27")
>>> clip = Timecode(29.97, "09:24:03:19")
>>> clip - vid
00:00:06;19
```


![image](https://user-images.githubusercontent.com/490588/68218200-3ba7f480-ffe4-11e9-88de-d3d211a81033.png)

This is the other web timecode calculator on the image: http://chxo.com/scripts/pTCcalc.php

But I'm not so sure the problem is the pytimecode calculation, at least on my case (29.97fps).

**Comment by fantopop** [comment]
@pathakumesh , hi!

I think there is no error but some confusion in usage. By adding `00:00:00:03` to `00:00:00:09` is it meant to shift the first one by 9 frames? If so, the correct answer can be achieved using `frame_number` attribute:

```
>>> TC = Timecode(25, '00:30:00:00')
>>> delta = Timecode(25, '01:00:00:00')
>>> 
>>> TC + delta
01:30:00:01
>>> TC + delta.frame_number
01:30:00:00
```

And in Michael Cinquin's calculator (which I am also using) I think this logic is implicitly applied, because this is the most likely scenario of adding and subtracting timecode values.

**Comment by eoyilmaz** [comment]
@pathakumesh , I agree with @fantopop 

I'll follow @fantopop 's examples.

Let's think about this, suppose that you have two clips that both start from 00:00:00:00. The first clips final frame has the timecode of 00:00:00:03, so it has 4 frames as 00:00:00:03 represents 4 frames, 00, 01, 02 and 03.

Similarly the second clips final frame has the timecode of 00:00:00:09 which represents 10 frames, 00, 01, 02 ... 08 and 09.

If you add up these two clips you should have 14 frames thus the final time code should be 00:00:00:13 and not 00:00:00:12.

I believe this is the difference.

**Comment by pathakumesh** [comment]
@eoyilmaz 
@fantopop 

I think this clears my confusion here. Closing this now.
