### ISSUE TITLE
Timecode calculation

### ISSUE THREAD

**Issue by aki-sud** [eoyilmaz/timecode#29]
Timecode(30,frames=0) gives 23:59:59:29 as the resultant timecode value.
Can you please explain why this is being calculated instead of 00:00:00:00 as the result??
(I am a newbie in timecode calculations, so please let me know in case any timecode calculations are wrong)

**Comment by aki-sud** [comment]
Please let me know as to why this discrepancy is occurring and is there any way to solve it ??

**Comment by aki-sud** [comment]
Is this library still working??

**Comment by eoyilmaz** [comment]
Yes this library is still working. Let me answer your question.

A TimeCode is a label for a frame. So 00:00:00:00 is the label generally for the first frame of a clip. So, you have a frame and its label is 00:00:00:00. If you have 0 frames, then there is no label thus no TimeCode.

And you are right in questioning the weird result of 23:59:59:29. And I think to guide the user, passing ``frames=0`` should actually raise an error. Fixed in 85901b0016dfd27f890385dea4dfd02dce9fabcf

Also created the 1.2.3 release to PyPI.
